# Generated by Django 4.2.6 on 2024-07-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_orderitems_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems",
            old_name="orderitems",
            new_name="product",
        ),
    ]
