# Generated by Django 4.2.6 on 2024-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_orderitems_orderitems_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
