# Generated by Django 4.2.7 on 2024-07-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cartitem",
            new_name="Cartitems",
        ),
    ]
