# Generated by Django 4.2.7 on 2024-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_rename_cartitem_cartitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
